### PR TITLE
Corrected Rules8-2-0-to-8-3-0.xls

### PR DESCRIPTION
**Pull request by mitchute**
Corrected for V8.2-8.3 GroundHeatExchanger:Vertical transition rules. Reference issue #5113

### CODE REVIEW

**Comment by mjwitte** [comment]
@mitchute Transition is now in the main EnergyPlus repo https://github.com/NREL/EnergyPlus/tree/develop/src/Transition
If you're game, you can modify https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/CreateNewIDFUsingRulesV8_2_0.f90 to match, or ask @Myoldmopar or myself to do so.

**Comment by mjwitte** [comment]
Oh, but old rules files aren't there in the main repo?

**Comment by Myoldmopar** [comment]
Not currently, but it's probably a fine idea to put those static-ish files in there.

**Comment by mjwitte** [comment]
@Myoldmopar Assigning this to you to figure out an appropriate place to store this corrected rules file.

**Comment by mjwitte** [comment]
@mitchute The rules stated here weren't consistent with what the transition source is doing.  I went ahead and updated it.

**Pull request closed without merging**
