### PR TITLE
In EP-Launch no longer delete all files with similar name as original…

### PR DESCRIPTION
**Pull request by JasonGlazer**
In EP-Launch no longer delete all files with similar name as original, and instead just run files created by ParametricPreprocessor. No changes to ParametricPreprocessor needed for this fix. This addresses  [EnergyPlus #4842](https://github.com/NREL/EnergyPlus/issues/4842)

### CODE REVIEW

**Comment by mjwitte** [comment]
Tested this and it fixes the problem.  Ready to merge unless you want to use this branch to remove the space in path test from #16

**Comment by JasonGlazer** [comment]
I am not sure what to do with the two branches. This one should include the code changes from #16 but I don't see them listed. So maybe I should just keep it open until we decide on that.

**Comment by Myoldmopar** [comment]
@jasonglazer, I haven't looked at this, but I'm going to be starting to
build release packages for testing today, so I can help test a windows
package later if it would help. And FYI the code in NREL/EnergyPlus is
closing this morning...

**Comment by JasonGlazer** [comment]
This pull request should fix both this issue and the one addressed by pull request #16 related to warning when in a directory that does not run EnergyPlus properly. 
https://github.com/NREL/EnergyPlus/issues/5109
The binary included address both also.

**Comment by mjwitte** [comment]
Tested this and it behaves as described.  But another twist.  If Create batch file is checked, *and* the idf file is located somewhere with full write permissions, then it will run successfully even when EnergyPlus is installed in Program Files.  But both of those conditions must be met.  I thought I had tried this before, but apparently not this combination.  We can stay with the current warning, or try to make it a little smarter.

Also, the current crash dialog needs some revisions.
image

It shouldn't lead with Please Report Crash.  I would delete that section entirely and replace it with something like this.  

**Check the EnergyPlus Installation**
Run an example file to determine if the problem is with this idf file or a more general problem with your EnergyPlus installation.  EnergyPlus works best when installed in a path with no spaces or special characters, and in a location that requires no special permission to write files.  

Also, the last section is not applicable since we don't have traceback now.  Perhaps it could be changed to.
**Check for System Messages**
You may activate 'Pause during Simulation' under the 'View' menu to see if any system messages give any useful information about the reason for the crash.

This would be nice for v8.4.0, but it could wait.

**Comment by JasonGlazer** [comment]
I am not sure we want to make the warning smarter or more precise. It really is about how EnergyPlus is installer and run. Once EP-Launch starts up it should run any file, any where.

As far as changing the crash dialog message. Can we make that a different issue to handle later?

**Comment by mjwitte** [comment]
OK.  We'll keep the warning logic as-is and see if we get any complaints.
The crash dialog revision are now [EnergyPlus #5224](https://github.com/NREL/EnergyPlus/issues/5224)

**Pull request merged**
