### PR TITLE
EP-Launch shows warning if in directory that does not have write permission or with spaces in path

### PR DESCRIPTION
**Pull request by JasonGlazer**
Related to [EnergyPlus #5109](https://github.com/NREL/EnergyPlus/issues/5109)

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@mjwitte Could you review and merge the pull request.

**Comment by mjwitte** [comment]
I tested this.
 1. Installed v8.3.3 in c;\windows\Program Files, then copied this new ep-launch to there.  Opened ep-launch and got the warning.
 2. Copied the new ep-launch into my main v8.3.0 install folder.  Opened ep-launch and no warning.
 3. I have idf files associated with the v8.3.0 ep-launch.  When I double-click an idf file, I get the warning, even though it's opening c:\energyplusv8-3-0\ep-launch.exe (it's the new ep-launch, but it's in a good directory).

**Comment by JasonGlazer** [comment]
For (3) what directory was the idf file in?

**Comment by mjwitte** [comment]
"C:\EnergyPlusV8-3-0\ExampleFiles\1ZoneEvapCooler.idf"

**Comment by JasonGlazer** [comment]
@mjwitte A simple change to address the issue with double clicking (although it took me a while to figure it out)

**Comment by mjwitte** [comment]
That checks out ok now.

**Comment by mjwitte** [comment]
So, I just noticed that all of my development folders are in a path with spaces in it, and it's triggering the warning.  ep-launch works just fine there, so maybe we should back out the spaces in the path test and just go with the write permission test, or add an option to turn it off.

**Comment by JasonGlazer** [comment]
@mjwitte Does it work with "Create Batch File to Run EnergyPlus" checked and unchecked?

**Comment by JasonGlazer** [comment]
@mjwitte I just tested and with that batch file option unchecked, it cannot run EnergyPlus. I will make the start up warning conditional on that.

**Comment by JasonGlazer** [comment]
Fixes are now included in #17

**Pull request merged**
