### PR TITLE
IDF Editor - new IP unit conversions, support unix line endings, and fix validity checking

### PR DESCRIPTION
**Pull request by JasonGlazer**
https://github.com/NREL/EnergyPlus/issues/5443

### CODE REVIEW

**Comment by JasonGlazer** [comment]
For IDD changes see:

https://github.com/NREL/EnergyPlus/pull/5509

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mjwitte I am making other fixes to IDF Editor and wonder if I should just add them to this pull request or create new pull requests? Since the pull request includes a binary file, it might be easier to just keep adding on to this one.

**Comment by Myoldmopar** [comment]
:+1: to just adding it here.

**Comment by JasonGlazer** [comment]
Addressed with the same pull request:

https://github.com/NREL/EnergyPlus/issues/5253

https://github.com/NREL/EnergyPlus/issues/5464

https://github.com/NREL/EnergyPlus/issues/5453

These all related to IDF Editor although not related to the unit conversions.

**Comment by mjwitte** [comment]
Tested the unix line endings #5453 and #5464 and the validity check #5253. These are ok.

**Comment by mjwitte** [comment]
@JasonGlazer Somehow, using this new IDF Editor reset my file association for idf files.  It was set to open ep-launch, but not it's opening idf editor 2.0.  Strange.  On Windows 10.

**Comment by JasonGlazer** [comment]
@mjwitte I really don't understand how using IDF Editor version 1.48a would have reset your file associations with IDF Editor 2.0. The only stuff it does with the registry saves the location and layout and recently used file list. It does not do anything with file associations.

**Comment by mjwitte** [comment]
@JasonGlazer I'll see if I can reproduce it with a specific sequence.

**Pull request merged**
