### PR TITLE
Appendix G Postprocessor - add error file and handle misaligned tables

### PR DESCRIPTION
**Pull request by JasonGlazer**
Addresses [EnergyPlus #2880](https://github.com/NREL/EnergyPlus/issues/2880)
Part one of fix is to add creation of error file from AppGPostProcess utility

Addresses [EnergyPlus #3568](https://github.com/NREL/EnergyPlus/issues/3658)
When the Appendix G Postprocessor sees that files are not aligned, it goes to the next table for each file. An error is produced indicating the number of lines skipped. 
Also errors and messages are now handled separately to avoid having flags showing that errors occurred all over.

### CODE REVIEW

**Comment by JasonGlazer** [comment]
Fix related to 

https://github.com/NREL/EnergyPlus/issues/2880

**Comment by JasonGlazer** [comment]
@mjwitte You may be the best person to test this. Do you mind being the reviewer?

**Comment by mjwitte** [comment]
Sure - will do.

**Comment by JasonGlazer** [comment]
Added a fix to the same pull request since still for AppGPostProcess. This time it fixes the #3658 bug:

https://github.com/NREL/EnergyPlus/issues/3658

When it sees that files are not aligned, it goes to the next table for each file. An error is produced indicating the number of lines skipped. 

Also errors and messages are now handled separately to avoid having flags showing that errors occurred all over.

**Comment by mjwitte** [comment]
@JasonGlazer The new appgpostprocess.exe won't run for me.  It's complaining about missing dlls:  libgfortran-3.dll and  libgcc_s_dw2-1.dll
@Myoldmopar Should this pull request be merging into the v8.5.0 branch instead of master?  Also, what have we done previously to get PRs from this repo into the release changelog?

**Comment by JasonGlazer** [comment]
@mjwitte Could you try this exe. I added

-static-libgcc -static-libgfortran

to the options which should statically link those libraries into the exe.

**Comment by mjwitte** [comment]
That runs now.

**Comment by mjwitte** [comment]
Tested this with a few different errors, it runs, produces output, and produces the new error file.  When there is a missing table in one of the files, no further tables are averaged.  Is that what's supposed to happen?

**Comment by JasonGlazer** [comment]
No it should just skip the missing table and continue averaging. Could you send me the test files that you were using?

**Comment by JasonGlazer** [comment]
The fix was not made to skip entire tables that are missing but instead just for rows of tables that are missing. The original issue was related to a row missing from a table because one of the four rotations resulted in one of the zones not having a cooling load (or maybe it was heating). So just a row was missing. If we have a case when the four files are generated parametrically but an entire table is missing, than I need to add some additional logic.

**Comment by mjwitte** [comment]
Oh I see.  I'll retest with the defect file.

**Comment by mjwitte** [comment]
@Myoldmopar Should this pull request be merging into the v8.5.0 branch instead of master? Also, what have we done previously to get PRs from this repo into the release changelog?

**Comment by mjwitte** [comment]
Can you send me the defect file?

**Comment by mjwitte** [comment]
Tests OK with defect file.  This is ready to merge once we settle which branch to merge into.

**Comment by mjwitte** [comment]
@JasonGlazer I tried to make a new pull request into the v8.5.0 branch, but that results in conflicts (due to master being behind some of the other branches).  So, please make a new branch starting with the current v8.5.0 branch and then copy your modified files into that and make a new pull request into the v8.5.0 branch.

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar I can do that but wouldn't it make more sense to update master to the v8.5.0 branch at this point? Or is there something in master we don't want to be part of the 8.5.0 release in EnergyPlusBuildSupport?

**Comment by Myoldmopar** [comment]
Sorry for the delay in comment.  @kbenne is there any reason that master branch shouldn't be brought up and used as the latest branch?  It seems like we should:
- pull master up to the latest version
- create tags for all the other branch states and delete the branches

All that said, I think the appG source should just be a part of NREL/EnergyPlus.  I understand the RealBasic and VB6 stuff sitting over here, but not Fortran.  We should add a target for that and keep it in the main repo.  If there's no reasons not to, I am happy to do that.  When the source is settled down in this PR, I'll remove it from this PR and move it over as-is to NREL/EnergyPlus and set up the CMake commands.  Then both of the PRs can merge.

Hopefully this repo dies at some point...

**Comment by mjwitte** [comment]
@Myoldmopar Just to be clear, the code here is ready to go.  Assigning this to you to move/merge when ready.

**Comment by Myoldmopar** [comment]
@JasonGlazer I merged in develop, and there were some binary conflicts related to EP-Launch.  I simply accepted the version of the files in this branch in order to _resolve_ the conflicts.  I think that should be just fine.

**Comment by JasonGlazer** [comment]
That seems reasonable to me.

**Comment by Myoldmopar** [comment]
Thanks @JasonGlazer I'm merging this now and I'll go back and clean up the whole AppG Fortran stuff whenever I can.  Too many moving parts right now...

**Pull request merged**
